# Generated by Django 4.1.3 on 2022-11-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icyangombwa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('papa', models.CharField(max_length=200)),
                ('mama', models.CharField(max_length=200)),
                ('umubyeyi_wa_batisimu', models.CharField(max_length=200)),
                ('parroise', models.CharField(max_length=200)),
                ('itariki_yamavuko', models.DateField()),
                ('batisimu', models.DateField()),
                ('Ukaristiya', models.DateField()),
                ('Gukomezwa', models.DateField()),
                ('batisimu_status', models.BooleanField(default=False)),
                ('Ukaristiya_status', models.BooleanField(default=False)),
                ('Gukomezwa_status', models.BooleanField(default=False)),
            ],
        ),
    ]
