# Generated by Django 4.1.3 on 2022-11-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ubukarani', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icyangombwa',
            old_name='name',
            new_name='amazina',
        ),
    ]
