# Generated by Django 4.1.3 on 2023-01-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ubukarani', '0003_ibyasabwe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibyasabwe',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'approved')], default='1', max_length=20),
        ),
    ]
