# Generated by Django 4.1.3 on 2023-01-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ubukarani', '0004_ibyasabwe_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibyasabwe',
            name='amazina',
            field=models.CharField(max_length=1000),
        ),
    ]
