# Generated by Django 4.1.3 on 2023-01-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ubukarani', '0005_alter_ibyasabwe_amazina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icyangombwa',
            old_name='amazina',
            new_name='prenom',
        ),
        migrations.AddField(
            model_name='icyangombwa',
            name='District',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icyangombwa',
            name='Nom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icyangombwa',
            name='province',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='icyangombwa',
            name='Ukaristiya',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='icyangombwa',
            name='batisimu',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='icyangombwa',
            name='itariki_yamavuko',
            field=models.DateField(null=True),
        ),
    ]
