# Generated by Django 4.1.3 on 2023-01-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ubukarani', '0006_rename_amazina_icyangombwa_prenom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icyangombwa',
            name='Vicus',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
