# Generated by Django 4.1.3 on 2023-01-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ubukarani', '0017_alter_ibyasabwe_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibyasabwe',
            name='owner_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ibyasabwe',
            name='status',
            field=models.CharField(choices=[('2', 'approved'), ('1', 'Pending')], default='1', max_length=20),
        ),
    ]
