# Generated by Django 4.1.3 on 2022-12-05 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Mass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mass',
            name='isomo_1',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mass',
            name='isomo_2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mass',
            name='ivanjiri',
            field=models.TextField(default='invanjiri'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mass',
            name='padiri',
            field=models.TextField(default='summary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mass',
            name='summary',
            field=models.TextField(default='umwanzuro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mass',
            name='umwanzuro',
            field=models.TextField(default='umwanzuro'),
            preserve_default=False,
        ),
    ]
