# Generated by Django 4.1.3 on 2022-12-05 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mass', '0002_mass_isomo_1_mass_isomo_2_mass_ivanjiri_mass_padiri_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mass',
            new_name='HolyMass',
        ),
    ]
