# Generated by Django 4.1.3 on 2022-12-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mass', '0003_rename_mass_holymass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HolyMass',
        ),
    ]
