# Generated by Django 4.1.3 on 2022-12-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Mass', '0004_delete_holymass'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolyMass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=7)),
                ('place', models.CharField(max_length=20)),
                ('padiri', models.TextField()),
                ('isomo_1', models.TextField()),
                ('isomo_2', models.TextField()),
                ('ivanjiri', models.TextField()),
                ('summary', models.TextField()),
                ('umwanzuro', models.TextField()),
            ],
        ),
    ]
