# Generated by Django 4.1.3 on 2023-01-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mass', '0007_mass_ivanjiri_verse_mass_verse_1_mass_verse_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mass',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mass',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
