# Generated by Django 4.1.3 on 2023-01-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mass', '0008_mass_date_alter_mass_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mass',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mass',
            name='time',
            field=models.TimeField(),
        ),
    ]
