# Generated by Django 4.1.3 on 2023-01-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='thumb',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
