# Generated by Django 4.1.3 on 2023-01-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_remove_event_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thumb',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
