# Generated by Django 4.1.3 on 2022-11-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='thumb',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
