# Generated by Django 4.1.3 on 2023-01-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('slug', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='messaging',
            name='reciever',
            field=models.CharField(max_length=1000),
        ),
    ]
