# Generated by Django 4.1.3 on 2023-01-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0002_room_alter_messaging_reciever'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messaging',
            name='sender',
            field=models.CharField(max_length=10000),
        ),
    ]
