# Generated by Django 4.1.3 on 2023-01-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0004_alter_room_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messaging',
            old_name='reciever',
            new_name='room',
        ),
        migrations.AddField(
            model_name='messaging',
            name='receiver',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
