# Generated by Django 4.1.3 on 2023-01-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0008_messaging_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='client_pending',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='staff_pending',
            field=models.IntegerField(null=True),
        ),
    ]
