# Generated by Django 4.1.3 on 2023-01-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0009_room_client_pending_room_staff_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='client_pending',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='staff_pending',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
